/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // Story 1
        System.out.println("------- Story 1 -------");
        Mobile mobile1 = new Mobile("story 1 mobile", "black", "Nokia");
        mobile1.call("Your mother is finding you.");
    }
}
